### ISSUE TITLE
After deploy Heroku - Unable to launch browser, error message: Failed to launch the browser process!

### ISSUE THREAD

**Issue by fsww-btamila** [frinyvonnick/node-html-to-image#100]
Hi,

I'm using node-html-to-image successfully created local App. It's working Good what I'm expected , but after deploy any server the following error will throw.

 (node:21) UnhandledPromiseRejectionWarning: Error: Unable to launch browser, error message: Failed to launch the browser process!
2021-02-10T16:06:35.195228+00:00 app[web.1]: /app/node_modules/puppeteer/.local-chromium/linux-737027/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory
2021-02-10T16:06:35.195229+00:00 app[web.1]: 
2021-02-10T16:06:35.195229+00:00 app[web.1]: 
2021-02-10T16:06:35.195230+00:00 app[web.1]: TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md
2021-02-10T16:06:35.195231+00:00 app[web.1]: 
2021-02-10T16:06:35.195231+00:00 app[web.1]:     at Cluster.<anonymous> (/app/node_modules/puppeteer-cluster/dist/Cluster.js:120:27)
2021-02-10T16:06:35.195232+00:00 app[web.1]:     at Generator.throw (<anonymous>)
2021-02-10T16:06:35.195233+00:00 app[web.1]:     at rejected (/app/node_modules/puppeteer-cluster/dist/Cluster.js:6:65)
2021-02-10T16:06:35.195233+00:00 app[web.1]:     at processTicksAndRejections (internal/process/task_queues.js:93:5)
2021-02-10T16:06:35.195234+00:00 app[web.1]: (Use `node --trace-warnings ...` to show where the warning was created)
2021-02-10T16:06:35.195581+00:00 app[web.1]: (node:21) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
2021-02-10T16:06:35.195727+00:00 app[web.1]: (node:21) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

How to solve this issue?
Can you please help me.

**Comment by frinyvonnick** [comment]
Hi @fsww-btamila 👋 

Thank you for opening this issue 🙏  Did you try the fixes described in this [issue](https://github.com/frinyvonnick/node-html-to-image/issues/49) or this [one](https://github.com/frinyvonnick/node-html-to-image/issues/88) that looks related to your topic. Please close this issue if it fixes it 😄

**Comment by fsww-btamila** [comment]
Actually I'm facing still above the error. If possible to give me a solution. 
Node version  is 12.16.1

**Comment by fsww-btamila** [comment]
> Hi @fsww-btamila 👋
> 
> Thank you for opening this issue 🙏 Did you try the fixes described in this [issue](https://github.com/frinyvonnick/node-html-to-image/issues/49) or this [one](https://github.com/frinyvonnick/node-html-to-image/issues/88) that looks related to your topic. Please close this issue if it fixes it 😄

**Comment by frinyvonnick** [comment]
@fsww-btamila node-html-to-image uses puppeteer to create the images. It seems to have issues opening chromium. You can look to the [troobleshooting section](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-on-heroku) of puppeteer. Hope you will find a solution. Don't forget to post here if you find something to help other users 😄

**Comment by frinyvonnick** [comment]
I close this issue. Feel free to reopen it.
