### ISSUE TITLE
throw new Error('Unable to get browser page');

### ISSUE THREAD

**Issue by Shadowplays4k** [frinyvonnick/node-html-to-image#109]
I have no idea why this is happening heres the error

```
[main 12:24:06] Z:\Personal\repos\testproj\node_modules\puppeteer-cluster\dist\Worker.js:44
                        throw new Error('Unable to get browser page');
                              ^

Error: Unable to get browser page
    at Worker.<anonymous> (Z:\Personal\repos\testproj\node_modules\puppeteer-cluster\dist\Worker.js:44:31)
    at Generator.next (<anonymous>)
    at fulfilled (Z:\Personal\repos\testproj\node_modules\puppeteer-cluster\dist\Worker.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)

```

thanks any help is appreciated

**Comment by frinyvonnick** [comment]
Hi @Shadowplays4k 👋 

Thank you for opening this issue 🙏  Can you share the code you wrote to have this error to help me reproduce it.

**Comment by mustafa-707** [comment]
its happens with me also this is my data 

OS : MacOS Big Sir
npm version : 6.14.13
node version : v14.17.0

its happens with me only when put this param : 

```
                        puppeteerArgs: {
                                   
                            args: [ '--no-sandbox',  '--disable-gpu' ],
                            defaultViewport:{                           
                                width:1920,
                                hight:1080,
                                deviceScaleFactor:2,
                                }, 
                        },
```
exactly when define `defaultViewport` as father of the width , hight ..etc params

**Comment by Shadowplays4k** [comment]
> @Shadowplays4k can you share environment information about the device your are running this code (OS, npm version, node version, ...)?

OS: windows server 22
npm version: the one that comes with node 14
node: 14

**Comment by frinyvonnick** [comment]
I released a new version of node-html-to-image (3.2.0) that updates puppeteer version which might fix your issue. Could you give it a try and see if it fixes your problem?

**Comment by igor9silva** [comment]
We're facing the same error when using `defaultViewport`. Anyone managed to use it?
I want to use scale or `isMobile`.

**Comment by josh231101** [comment]
I have the same error, I am using a docker image.

**Comment by josh231101** [comment]
I found the solution. If you are using a Docker image call it inside an ECS in AWS and its giving you an error launching de puppeteer chromium.

Update your dockerfile with this lines:
```
RUN apk add --no-cache chromium
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true
ENV CHROMIUM_PATH /usr/bin/chromium-browser
``` 

In case you are using the library pass the puppeteer args like this:
```typescript
nodeHtmlToImage({
      puppeteerArgs: {
        executablePath: '/usr/bin/chromium-browser',
        args: ['--no-sandbox', '--disable-gpu'], // This is important
      },
      output: filePath,
      html,
    })
```
