### ISSUE TITLE
Error: Unable to launch browser, error message: Unsupported platform: android

### ISSUE THREAD

**Issue by potato-baby** [frinyvonnick/node-html-to-image#139]
```js
~ $ node ~/node-html-to-image/example.js
/data/data/com.termux/files/home/node_modules/puppeteer-cluster/dist/Cluster.js:120
                    throw new Error(`Unable to launch browser, error message: ${err.message}`);
                          ^


    at Cluster.<anonymous> (/data/data/com.termux/files/home/node_modules/puppeteer-cluster/dist/Cluster.js:120:27)
    at Generator.throw (<anonymous>)
    at rejected (/data/data/com.termux/files/home/node_modules/puppeteer-cluster/dist/Cluster.js:6:65)
```

**Comment by frinyvonnick** [comment]
Hi @potato-baby 👋 

Sorry for the long response. Did you manage to fix your problem? Maybe you can share here how you did it 😄

**Comment by potato-baby** [comment]
i forgot 😐
i will have to start it all again
