### ISSUE TITLE
Heroku

### ISSUE THREAD

**Issue by StrangerGithuber** [frinyvonnick/node-html-to-image#150]
Hello
I am using this project in a discord bot and I am hosting on the Heroku cloud however whenever I am using this node-html-to-image then I get an error:

```
2022-01-09T18:31:59.191338+00:00 app[service.1]: /app/node_modules/puppeteer-cluster/dist/Cluster.js:120
2022-01-09T18:31:59.191342+00:00 app[service.1]:                     throw new Error(`Unable to launch browser, error message: ${err.message}`);
2022-01-09T18:31:59.191343+00:00 app[service.1]:                           ^
2022-01-09T18:31:59.191344+00:00 app[service.1]: 
2022-01-09T18:31:59.191344+00:00 app[service.1]: Error: Unable to launch browser, error message: Failed to launch the browser process!
2022-01-09T18:31:59.191363+00:00 app[service.1]: /app/node_modules/puppeteer/.local-chromium/linux-737027/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory
2022-01-09T18:31:59.191364+00:00 app[service.1]: 
2022-01-09T18:31:59.191364+00:00 app[service.1]: 
2022-01-09T18:31:59.191364+00:00 app[service.1]: TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md
2022-01-09T18:31:59.191364+00:00 app[service.1]: 
2022-01-09T18:31:59.191365+00:00 app[service.1]:     at Cluster.<anonymous> (/app/node_modules/puppeteer-cluster/dist/Cluster.js:120:27)
2022-01-09T18:31:59.191366+00:00 app[service.1]:     at Generator.throw (<anonymous>)
2022-01-09T18:31:59.191367+00:00 app[service.1]:     at rejected (/app/node_modules/puppeteer-cluster/dist/Cluster.js:6:65)
2022-01-09T18:31:59.191368+00:00 app[service.1]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-01-09T18:31:59.191372+00:00 app[service.1]: 
```

Does someone hosting on the heroku and having this issue with the node-html-to-image?
Did someone figure out what to do?

**Comment by StrangerGithuber** [comment]
Oh ok, I needed to add this: https://github.com/jontewks/puppeteer-heroku-buildpack
