### ISSUE TITLE
Unable to get browser page

### ISSUE THREAD

**Issue by s1103179** [frinyvonnick/node-html-to-image#172]
My code does nothing and after a while leaves the following error:
`(node:67808) UnhandledPromiseRejectionWarning: Error: Unable to get browser page
    at Worker.<anonymous> (G:\ONEDRIVE\\{DIRECTORY}\School\html-to-image-test\node_modules\puppeteer-cluster\dist\Worker.js:41:31)
    at Generator.next (<anonymous>)
    at fulfilled (G:\ONEDRIVE\{DIRECTORY}\School\html-to-image-test\node_modules\puppeteer-cluster\dist\Worker.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:67808) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:67808) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`
I tried creating a completely fresh project and only put in the following code in my index.js. This code is traight from the readme but still produced the exact same error. Weirdly, my code worked perfectly fine yesterday.

`const nodeHtmlToImage = require('node-html-to-image')

nodeHtmlToImage({
  output: './image.png',
  html: '<html><body>Hello world!</body></html>'
})
  .then(() => console.log('The image was created successfully!'))`

**Comment by rChahine** [comment]
@Onctaaf did you find a solution ?

**Comment by frinyvonnick** [comment]
I just released [3.3.0](https://github.com/frinyvonnick/node-html-to-image/releases/tag/v3.3.0) version which contain a feature to customise which puppeteer library node-html-to-image uses. It might help you making node-html-to-image work in a cloud context. Here is the documentation : https://github.com/frinyvonnick/node-html-to-image#using-different-puppeteer-libraries

Could you close the issue if it fixes it, please?

**Comment by shaikdvara** [comment]
issue, not at fixed

**Comment by frinyvonnick** [comment]
@shaikdvara could you provide more information that might help fixing the issue?

**Comment by dgsmith7** [comment]
I had this same problem.  My project was working fine and this problem happened "out of the blue".  For me, the solution was this:  I deleted my node_modules folder, deleted my package-lock.json, then executed `npm install.`  Once everything was reinstalled the project worked fine.

**Comment by frinyvonnick** [comment]
This has been inactive for over a year and predates several releases (the library is now on v6 with Puppeteer 25). Closing to keep the tracker tidy — if it's still relevant on the latest version, please reopen with an up-to-date reproduction. Thanks!
