### ISSUE TITLE
Unable to launch browser, error message: Failed to launch the browser process!

### ISSUE THREAD

**Issue by evgeniy-kolmak** [frinyvonnick/node-html-to-image#219]
Version 4.0.0.
Locally everything works well. But when deploying to a server or docker container g I get an error message.

`Error: Unable to launch browser, error message: Failed to launch the browser process!
rosetta error: failed to open elf at /lib64/ld-linux-x86-64.so.2

TROUBLESHOOTING: https://pptr.dev/troubleshooting

    at Cluster.<anonymous> (/usr/src/app/node_modules/puppeteer-cluster/src/Cluster.ts:168:19)
    at Generator.throw (<anonymous>)
    at rejected (/usr/src/app/node_modules/puppeteer-cluster/dist/Cluster.js:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)`

An older version cannot be installed because it points to deprecated packages.

**Comment by waqas-theneosolutions** [comment]
Any updates? facing same issue when deployed to server (ubuntu)

```
2|backend1 | TROUBLESHOOTING: https://pptr.dev/troubleshooting
2|backend1 | 
2|backend1 | Error: Unable to launch browser, error message: Failed to launch the browser process!
2|backend1 | [113690:113690:0613/144844.399980:FATAL:zygote_host_impl_linux.cc(127)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/main/docs/linux/suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
2|backend1 | [0613/144844.407220:ERROR:file_io_posix.cc(144)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory (2)
2|backend1 | [0613/144844.407376:ERROR:file_io_posix.cc(144)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: No such file or directory (2)
2|backend1 | 
2|backend1 | 
2|backend1 | TROUBLESHOOTING: https://pptr.dev/troubleshooting
2|backend1 | 
2|backend1 |     at Cluster.<anonymous> (/home/ubuntu/Hallabackend/node_modules/puppeteer-cluster/src/Cluster.ts:168:19)
2|backend1 |     at Generator.throw (<anonymous>)
2|backend1 |     at rejected (/home/ubuntu/Hallabackend/node_modules/puppeteer-cluster/dist/Cluster.js:6:65)
2|backend1 |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by evgeniy-kolmak** [comment]
You can solve the problem by installing **Chromium**. 

### Ubuntu 

``` 
sudo apt install chromium-browser
```

For any environment (vps or docker container).

**Comment by waqas-theneosolutions** [comment]
I did installed chromium but then I got another error 
```
Error: Unable to launch browser, error message: Failed to launch the browser process!
2|backend1  | [109360:109360:0613/080650.626809:FATAL:zygote_host_impl_linux.cc(127)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/main/docs/linux/suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
2|backend1  | [0613/080650.634302:ERROR:file_io_posix.cc(144)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory (2)
2|backend1  | [0613/080650.634352:ERROR:file_io_posix.cc(144)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: No such file or directory (2)
2|backend1  | TROUBLESHOOTING: https://pptr.dev/troubleshooting
2|backend1  |     at Cluster.<anonymous> (/home/ubuntu/Hallabackend/node_modules/puppeteer-cluster/src/Cluster.ts:168:19)
2|backend1  |     at Generator.throw (<anonymous>)
2|backend1  |     at rejected (/home/ubuntu/Hallabackend/node_modules/puppeteer-cluster/dist/Cluster.js:6:65)
2|backend1  |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
```
After spending hour to resolve this problem, I cam across a similar issue reported and resolved at stackoverflow <https://stackoverflow.com/questions/59979188/error-failed-to-launch-the-browser-process-puppeteer> **Solution** Add path to installed chromium within options resolved issue.
```
   const nodeHtmlToImageOptions: any = {
      output: '/image.png', // file for saving image
      html: html,
    };
    // Added 'puppeteerArgs' to resolve issue at server side for creating PNG 
    // Check the path where 'chromium-browser' is installed using command `which chromium-browser`
    // Paste that path for executablePath
    nodeHtmlToImageOptions.puppeteerArgs = {
      executablePath: '/usr/bin/chromium-browser',
    };
    nodeHtmlToImage(nodeHtmlToImageOptions).then(async () => {
    // Do something with response
    });
  ```

**Comment by frinyvonnick** [comment]
Did you check the troubleshooting section of Puppeteer documentation? https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

**Comment by frinyvonnick** [comment]
This is a Chromium-launch/environment issue rather than a bug in this library — it commonly appears in Docker, serverless and other restricted environments. Puppeteer's troubleshooting guide covers the usual fixes (missing system libraries, `--no-sandbox`, custom `executablePath`): https://pptr.dev/troubleshooting

You can forward Puppeteer options via `puppeteerArgs`, e.g.:

```js
nodeHtmlToImage({ html: '...', puppeteerArgs: { args: ['--no-sandbox'] } })
```

Closing as an environment issue — happy to help further in the thread if needed.
