### ISSUE TITLE
Error: Unable to get browser page

### ISSUE THREAD

**Issue by iamparthaonline** [frinyvonnick/node-html-to-image#68]
Getting this error,

```
> node index.js

Listening on 5000
(node:4018) UnhandledPromiseRejectionWarning: Error: Unable to get browser page
    at Worker.<anonymous> (/Users/partharoy/Desktop/dev/b/bCard/node_modules/puppeteer-cluster/dist/Worker.js:44:31)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/partharoy/Desktop/dev/bengalbyte/bbCard/node_modules/puppeteer-cluster/dist/Worker.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:4018) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4018) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by iamparthaonline** [comment]
Found the issue, it's happening when I'm providing a custom puppeteerArgs ( Which is needed for production ). 
I will do a PR if that's Ok. 


```
const puppeteerArgs = {
    args: [
        '--no-sandbox',
        '--disable-setuid-sandbox',
        '--disable-dev-shm-usage',
        '--disable-accelerated-2d-canvas',
        '--no-first-run',
        '--no-zygote',
        '--single-process',
        '--disable-gpu'
    ],
    headless: false,
    ignoreHTTPSErrors: true
};
```
