### ISSUE TITLE
Can't run it inside docker container

### ISSUE THREAD

**Issue by yang093** [frinyvonnick/node-html-to-image#90]

**Comment by joshk0** [comment]
I had success running it in a Docker container. I started from [zenika/alpine-chrome:with-node](https://github.com/Zenika/alpine-chrome) and made sure to set the arguments:

```
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD 1
ENV PUPPETEER_EXECUTABLE_PATH /usr/bin/chromium-browser
```

**Comment by frinyvonnick** [comment]
@yang093 does the comment @joshk0 helped you to fix your issue?

**Comment by ilyapavkin** [comment]
@frinyvonnick just for context:
```
app_1    | Request GET /api/photos/602ab3320544daf2e61beb89 failed with status code 500. Error: Unable to launch browser, error message: Failed to launch the browser process!
app_1    | [0215/204717.308697:FATAL:zygote_host_impl_linux.cc(116)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux/suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
app_1    | #0 0x5624452668f9 base::debug::CollectStackTrace()
app_1    | #1 0x5624451caae3 base::debug::StackTrace::StackTrace()
app_1    | #2 0x5624451dc865 logging::LogMessage::~LogMessage()
app_1    | #3 0x562446ac74ae service_manager::ZygoteHostImpl::Init()
app_1    | #4 0x562444db5627 content::ContentMainRunnerImpl::Initialize()
app_1    | #5 0x562444e032fa service_manager::Main()
app_1    | #6 0x562444db3c41 content::ContentMain()
app_1    | #7 0x562444e02135 headless::(anonymous namespace)::RunContentMain()
app_1    | #8 0x562444e01ddd headless::HeadlessShellMain()
app_1    | #9 0x562442870a67 ChromeMain
app_1    | #10 0x7fd3aa2322e1 __libc_start_main
app_1    | #11 0x5624428708aa _start
app_1    | 
app_1    | Received signal 6
app_1    | #0 0x5624452668f9 base::debug::CollectStackTrace()
app_1    | #1 0x5624451caae3 base::debug::StackTrace::StackTrace()
app_1    | #2 0x5624452664a0 base::debug::(anonymous namespace)::StackDumpSignalHandler()
app_1    | #3 0x7fd3b07dc0e0 (/lib/x86_64-linux-gnu/libpthread-2.24.so+0x110df)
app_1    | #4 0x7fd3aa244fff gsignal
app_1    | #5 0x7fd3aa24642a abort
app_1    | #6 0x5624452653f5 base::debug::BreakDebugger()
app_1    | #7 0x5624451dcd04 logging::LogMessage::~LogMessage()
app_1    | #8 0x562446ac74ae service_manager::ZygoteHostImpl::Init()
app_1    | #9 0x562444db5627 content::ContentMainRunnerImpl::Initialize()
app_1    | #10 0x562444e032fa service_manager::Main()
app_1    | #11 0x562444db3c41 content::ContentMain()
app_1    | #12 0x562444e02135 headless::(anonymous namespace)::RunContentMain()
app_1    | #13 0x562444e01ddd headless::HeadlessShellMain()
app_1    | #14 0x562442870a67 ChromeMain
app_1    | #15 0x7fd3aa2322e1 __libc_start_main
app_1    | #16 0x5624428708aa _start
app_1    |   r8: 0000000000000000  r9: 00007ffdcd45e950 r10: 0000000000000008 r11: 0000000000000246
app_1    |  r12: 00007ffdcd45fc08 r13: 00007ffdcd45ebe0 r14: 00007ffdcd45fc10 r15: aaaaaaaaaaaaaaaa
app_1    |   di: 0000000000000002  si: 00007ffdcd45e950  bp: 00007ffdcd45eb90  bx: 0000000000000006
app_1    |   dx: 0000000000000000  ax: 0000000000000000  cx: 00007fd3aa244fff  sp: 00007ffdcd45e9c8
app_1    |   ip: 00007fd3aa244fff efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
app_1    |  trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
app_1    | [end of stack trace]
app_1    | Calling _exit(1). Core file will not be generated.
app_1    | 
app_1    | 
app_1    | TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md
app_1    | 
app_1    |     at Cluster.<anonymous> (/home/node/app/node_modules/puppeteer-cluster/dist/Cluster.js:120:27)
app_1    |     at Generator.throw (<anonymous>)
app_1    |     at rejected (/home/node/app/node_modules/puppeteer-cluster/dist/Cluster.js:6:65)
app_1    |     at processTicksAndRejections (internal/process/task_queues.js:97:5)```

**Comment by sBx99** [comment]
Hey @frinyvonnick, @yang093, and @ilyapavkin! I was having the same issue a week back, but I was able to run it after using @joshk0 's tip and looking around for a bit. Using [this code](https://github.com/Zenika/alpine-chrome/blob/master/with-puppeteer/Dockerfile), I was able to create this Dockerfile:

```Dockerfile
FROM zenika/alpine-chrome:with-node

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD 1
ENV PUPPETEER_EXECUTABLE_PATH /usr/bin/chromium-browser

WORKDIR /usr/src/app
COPY --chown=chrome package*.json ./

RUN npm install
COPY --chown=chrome . ./

ENTRYPOINT ["tini", "--"]
CMD ["npm", "start"]
```

Also, these were the puppeteer args I added to the function, since the function wasn't running in the container before I did this:

```javascript
puppeteerArgs: {
            headless: true,
            args: [
                "--no-sandbox",
                "--disable-setuid-sandbox",
                "--headless",
                "--disable-gpu",
                "--disable-dev-shm-usage",
            ],
        },
```
I hope this helps!

**Comment by frinyvonnick** [comment]
It could be interesting to add explanation on this topic in the README?

**Comment by mhrsntrk** [comment]
@sBx99 suggestion worked for me.

But right now, fonts doesn't show up properly inside the docker container. I think this issue related to alpine. Are there someone has the same issue with fonts?

**Comment by ZainUrRehmanKhan** [comment]
This is my working docker file:

```
`FROM node:16-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN apk update && \
    apk upgrade -U && \
    apk add ca-certificates ffmpeg libwebp libwebp-tools && \
    rm -rf /var/cache/*

RUN apk add python3
RUN apk add build-base

RUN npm install

COPY . .

RUN npm run build

CMD ["node", "dist/main"]`
```

I tried different solutions but it's not working, Can someone tell how can I fix this? I tried the solution above but I think I'm mission something

I'm getting is error:

![Screenshot from 2022-02-18 15-23-03](https://user-images.githubusercontent.com/67098758/154680786-7580a420-edc5-4d47-89ae-cb3c7fea8bc7.png)

**Comment by Nixum** [comment]
`nodeHtmlToImage({
                    html: content,
                    puppeteerArgs: {
                        args: [
                            '--no-sandbox',
                            '--disable-setuid-sandbox',
                            '--disable-dev-shm-usage',
                            '--disable-gpu'
                        ]
                    }
                })
`
when i set the puppeteerArgs in nodeHtmlToImage func, i fix this.
I hope this helps!

**Comment by ZainUrRehmanKhan** [comment]
@Nixum Thanks

**Comment by KenDodman** [comment]
Gotten things working on a Rpi 4 arm64 running docker
Here is my dockerfile

`FROM node:17.4.0
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD 1
ENV PUPPETEER_EXECUTABLE_PATH /usr/bin/chromium

WORKDIR /app
COPY package.json /app
RUN npm install puppeteer
RUN npm install
RUN apt-get update
RUN apt-get install chromium --yes
COPY . /app
EXPOSE 3001
CMD ["npm", "start"]
`

Using the htmltoimage options of 

`puppeteerArgs: {
            headless: true,
            args: [
                "--no-sandbox",
                "--disable-setuid-sandbox",
                "--headless",
                "--disable-gpu",
                "--disable-dev-shm-usage",
            ]
        }`

**Comment by roninjin10** [comment]
I'm struggling to get this to work on latest version (including building latest commit) even with some of the tips in this thread.   Trying older versions of puppateer.   The latest version on alpine I think is not possible to get working.   I'm trying older versions that have older versions of puppateer now.

**Comment by ZainUrRehmanKhan** [comment]
@roninjin10
You can try getting into your container and find if the chromium is in the correct location `/usr/bin/chromium` or somewhere else.
You can also check it's `chromium-browser` or just `chromium`

I'm using [alpine version ](node:16-alpine) and it's working. 
`RUN apk add chromium`

```
puppeteerArgs: {
  executablePath: '/usr/bin/chromium-browser',
  args: ['--no-sandbox', '--disable-setuid-sandbox'],
}
```

**Comment by roninjin10** [comment]
@ZainUrRehmanKhan 
Yea still having issues.   Your advice was good though. chromium-browser vs chromium was a bug.

Dockerfile
```
FROM --platform=linux/x86-64 node:16.17.1-alpine3.15 as base

RUN apk update && \
  apk upgrade -U \
  ca-certificates ffmpeg libwebp libwebp-tools
RUN apk --no-cache add chromium
RUN apk --no-cache add curl jq python3 ca-certificates git make gcc musl-dev linux-headers bash build-base

WORKDIR /opt/optimism

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD 1
ENV PUPPETEER_EXECUTABLE_PATH /usr/bin/chromium-browser
ENV CHROME_BIN /usr/bin/chromium-browser

COPY tsconfig.json package.json yarn.lock .npmrc ./
COPY packages/contracts/package.json packages/contracts/tsconfig.json packages/contracts/
COPY packages/nft-image-render/package.json packages/nft-image-render/tsconfig.json packages/nft-image-render/
COPY packages/tokenlist packages/tokenlist/
COPY packages/backend/package.json packages/backend/tsconfig.json packages/backend/

RUN yarn install --frozen-lockfile

# Build @gateway/backend & @gateway/contracts
COPY ./packages/contracts packages/contracts/
COPY ./packages/nft-image-render packages/nft-image-render/
COPY ./packages/backend packages/backend/
COPY ./packages/tokenlist packages/tokenlist/

RUN yarn workspace @gateway/backend run build

# Start @gateway/backend
EXPOSE $PORT
CMD ["yarn", "workspace", "@gateway/backend","run", "start:ci"]

```

And here is my code

```
 return nodeHtmlToImage({
      type: 'png',
      // .nft-image-render
      selector: `.${nftImageClass}`,
      puppeteerArgs: {
        headless: true,
        executablePath: '/usr/bin/chromium-browser',
        args: [
          '--disable-gpu',
          '--disable-dev-shm-usage',
          '--disable-setuid-sandbox',
          '--no-sandbox',
          '--headless',
        ],
      },
      html: `
        <!DOCTYPE html>
        <html lang="en">
          <head>
            <style>
              ${nftImageCss}
            </style>
          </head>
          <body>
            ${ReactDOMServer.renderToString(
              <NFTImageRender
                isPNG={false}
                imageUri={imageUri}
                {...optimistNftProps}
              />,
            )}
          </body>
        </html>`,
    })

```

**Comment by roninjin10** [comment]
My latest run got a different error

I changed the options to this:

```
            headless: true,
            args: [
                '--disable-gpu',
                '--disable-dev-shm-usage',
                '--disable-setuid-sandbox',
                '--no-sandbox',
                '--headless',
            ],
```
And got this error which is different
```
[
    {
        "error": {
            "json": {
                "message": "Unable to launch browser, error message: Failed to launch the browser process!\nqemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped\nqemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped\n[1201/204236.827090:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory\n[1201/204236.834224:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory\n[1201/204236.866902:warning:dns_config_service_linux.cc(427)] Failed to read DnsConfig.\n[1201/204236.908122:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib/chromium/libGLESv2.so: Error loading shared library /usr/lib/chromium/libGLESv2.so: No such file or directory\nAssertion 'r == 0 || r == 95' failed at ../src/pulsecore/mutex-posix.c:57, function pa_mutex_new(). Aborting.\nqemu: uncaught target signal 6 (Aborted) - core dumped\n\n\nTROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md\n",
                "code": -32603,
                "data": {
                    "code": "INTERNAL_SERVER_ERROR",
                    "httpStatus": 500,
                    "path": "nftbuilder.upload"
                }
            }
        }
    }
]
```

**Comment by frinyvonnick** [comment]
In version 4.0.0 I updated puppeeteer to version 21.0.1. It might help you in some way?

**Comment by roninjin10** [comment]
Oh I did get this working. Forgot to update. Here. If anybody has issues ping me and I can send you the combination of dockerfile plus runtime config that got it working.

**Comment by roninjin10** [comment]
One issue I had btw was that I had a working docker config multiple times following advice in this thread but it still failed on macOS on max silicone specifically without me realizing it was macOS based issues

**Comment by frinyvonnick** [comment]
Why can't you post it here @roninjin10?

**Comment by frinyvonnick** [comment]
This is a Chromium-launch/environment issue rather than a bug in this library — it commonly appears in Docker, serverless and other restricted environments. Puppeteer's troubleshooting guide covers the usual fixes (missing system libraries, `--no-sandbox`, custom `executablePath`): https://pptr.dev/troubleshooting

You can forward Puppeteer options via `puppeteerArgs`, e.g.:

```js
nodeHtmlToImage({ html: '...', puppeteerArgs: { args: ['--no-sandbox'] } })
```

Closing as an environment issue — happy to help further in the thread if needed.
